services:
  db: #can be used as hostname for the database connection
    image: postgres:17.10-bookworm #docker will use version 17.10 of postgres image with bookworm tag
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - simple-web-app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  db_test:
    image: postgres:17.10-bookworm
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
          initial_sync: true
        - action: sync
          path: ./backend/tests
          target: /app/tests
          initial_sync: true
        - action: sync
          path: ./backend/main.py
          target: /app/main.py
          initial_sync: true
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/requirements-dev.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          initial_sync: true
        - action: sync
          path: ./frontend/public
          target: /app/public
          initial_sync: true
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
        - action: rebuild
          path: ./frontend/vite.config.ts
        - action: rebuild
          path: ./frontend/tsconfig.json
        - action: rebuild
          path: ./frontend/tsconfig.app.json

volumes:
  simple-web-app_postgres_data:
